# Generated by Django 3.2 on 2021-06-13 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ManyToManyField(related_name='my_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
